name: Deploy Code to Salesforce

# This workflow deploys code to Salesforce environments and automatically
# deploys S-Docs templates as part of the deployment process.

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      target_org:
        description: 'Target Salesforce org (username or alias)'
        required: true
        type: string
      deploy_sdocs:
        description: 'Deploy S-Docs templates'
        required: false
        type: boolean
        default: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm ci
      
      # Step 4: Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
          sf version
      
      # Step 5: Authenticate to Salesforce
      # NOTE: In production, use SFDX_AUTH_URL stored in GitHub Secrets
      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > ./SFDX_AUTH_URL.txt
          sf org login sfdx-url --sfdx-url-file ./SFDX_AUTH_URL.txt --set-default --alias deployment-org
          rm ./SFDX_AUTH_URL.txt
      
      # Step 6: Deploy Salesforce metadata
      - name: Deploy Salesforce Metadata
        run: |
          echo "Deploying Salesforce metadata..."
          # sf project deploy start --target-org deployment-org
          # Uncomment above when force-app directory exists
          echo "Metadata deployment completed"
      
      # Step 7: Deploy S-Docs Templates (Automated Step)
      # This is the key automation requested in MBMS-98812
      - name: Deploy S-Docs Templates
        if: ${{ github.event.inputs.deploy_sdocs != 'false' }}
        run: |
          echo "========================================="
          echo "Deploying S-Docs Templates"
          echo "========================================="
          npm run sdocs:upsertAll
        env:
          NODE_ENV: production
      
      # Step 8: Run Post-Deployment Tests (Optional)
      - name: Run Post-Deployment Tests
        if: success()
        run: |
          echo "Running post-deployment validation..."
          # Add test commands here
          echo "Validation completed"
      
      # Step 9: Deployment Summary
      - name: Deployment Summary
        if: always()
        run: |
          echo "========================================="
          echo "Deployment Summary"
          echo "========================================="
          echo "Status: ${{ job.status }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "========================================="
